[package]
name = "kak-tree-sitter"
description = "kakoune tree-sitter server"
license = "CC0-1.0"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.2.4", features = ["derive"] }
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
tempfile = "3.5.0"
