[package]
name = "kak-tree-sitter"
description = "kakoune tree-sitter server"
license = "CC0-1.0"
version = "0.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.2.4", features = ["derive"] }
